### PR TITLE
Feature/ts

### PR DESCRIPTION
**Pull request by jonas-app**
Port tests and convert project to TypeScript.

### CODE REVIEW

**Review by TimSusa — APPROVED** [review]

**Comment by Nift** [comment]
Any news on this @TimSusa and @jonas-arkulpa ?

**Comment by jonas-app** [comment]
@Nift This is mergeable and I can make a new release today.
There are no breaking changes in this PR.

**Comment by Nift** [comment]
@jonas-arkulpa That would be awesome! 
I forked the repo to merge the PR myself and it seems to work nicely.

**Comment by jonas-app** [comment]
@Nift 👍 thx for the feedback.

**Comment by jonas-app** [comment]
@Nift Just published as version 1.1.0 to npm.
https://www.npmjs.com/package/@axelspringer/graphql-google-pubsub/v/1.1.0

**Comment by TimSusa** [comment]
Gentleman, 

sry for the delay. All this seems to be looking very nice to me at first glance. @Nift Welcome! @jonas-arkulpa Can we connect together these days, about taking the new version into account for Editor-Article?

Thanks!

**Pull request merged**
